#!/usr/bin/env python3
import csv
from datetime import datetime
import sys


# set_name_to_code = {
#     # shiny set name : moxfield set name
#     "Duskmourn House of Horror": "dsk",
# }

set_name_to_code = {
    'Limited Edition Alpha': 'LEA',
    'Limited Edition Beta': 'LEB',
    'Unlimited Edition': '2ED',
    'Revised Edition': '3ED',
    'Fourth Edition': '4ED',
    'Fifth Edition': '5ED',
    'Classic Sixth Edition': '6ED',
    'Seventh Edition': '7ED',
    'Eighth Edition': '8ED',
    'Ninth Edition': '9ED',
    'Tenth Edition': '10E',
    'Magic 2010': 'M10',
    'Magic 2011': 'M11',
    'Magic 2012': 'M12',
    'Magic 2013': 'M13',
    'Magic 2014': 'M14',
    'Magic 2015': 'M15',
    'Magic Origins': 'ORI',
    'Core Set 2019': 'M19',
    'Core Set 2020': 'M20',
    'Core Set 2021': 'M21',
    'Magic: The Gathering Foundations': 'FDN',
    'Arabian Nights': 'ARN',
    'Antiquities': 'ATQ',
    'Legends': 'LEG',
    'The Dark': 'DRK',
    'Fallen Empires': 'FEM',
    'Ice Age': 'ICE',
    'Homelands': 'HML',
    'Alliances': 'ALL',
    'Mirage': 'MIR',
    'Visions': 'VIS',
    'Weatherlight': 'WTH',
    'Tempest': 'TMP',
    'Stronghold': 'STH',
    'Exodus': 'EXO',
    "Urza's Saga": 'USG',
    "Urza's Legacy": 'ULG',
    "Urza's Destiny": 'UDS',
    'Mercadian Masques': 'MMQ',
    'Nemesis': 'NEM',
    'Prophecy': 'PCY',
    'Invasion': 'INV',
    'Planeshift': 'PLS',
    'Apocalypse': 'APC',
    'Odyssey': 'ODY',
    'Torment': 'TOR',
    'Judgment': 'JUD',
    'Onslaught': 'ONS',
    'Legions': 'LGN',
    'Scourge': 'SCG',
    'Mirrodin': 'MRD',
    'Darksteel': 'DST',
    'Fifth Dawn': '5DN',
    'Champions of Kamigawa': 'CHK',
    'Betrayers of Kamigawa': 'BOK',
    'Saviors of Kamigawa': 'SOK',
    'Ravnica: City of Guilds': 'RAV',
    'Guildpact': 'GPT',
    'Dissension': 'DIS',
    'Coldsnap': 'CSP',
    'Planar Chaos': 'PLC',
    'Future Sight': 'FUT',
    'Lorwyn': 'LRW',
    'Morningtide': 'MOR',
    'Shadowmoor': 'SHM',
    'Eventide': 'EVE',
    'Shards of Alara': 'ALA',
    'Conflux': 'CON',
    'Alara Reborn': 'ARB',
    'Zendikar': 'ZEN',
    'Worldwake': 'WWK',
    'Rise of the Eldrazi': 'ROE',
    'Scars of Mirrodin': 'SOM',
    'Mirrodin Besieged': 'MBS',
    'New Phyrexia': 'NPH',
    'Innistrad': 'ISD',
    'Dark Ascension': 'DKA',
    'Avacyn Restored': 'AVR',
    'Return to Ravnica': 'RTR',
    'Gatecrash': 'GTC',
    "Dragon's Maze": 'DGM',
    'Theros': 'THS',
    'Born of the Gods': 'BNG',
    'Journey into Nyx': 'JOU',
    'Khans of Tarkir': 'KTK',
    'Fate Reforged': 'FRF',
    'Dragons of Tarkir': 'DTK',
    'Battle for Zendikar': 'BFZ',
    'Oath of the Gatewatch': 'OGW',
    'Shadows over Innistrad': 'SOI',
    'Eldritch Moon': 'EMN',
    'Kaladesh': 'KLD',
    'Aether Revolt': 'AER',
    'Amonkhet': 'AKH',
    'Hour of Devastation': 'HOU',
    'Ixalan': 'XLN',
    'Rivals of Ixalan': 'RIX',
    'Dominaria': 'DOM',
    'Guilds of Ravnica': 'GRN',
    'Ravnica Allegiance': 'RNA',
    'War of the Spark': 'WAR',
    'Throne of Eldraine': 'ELD',
    'Theros Beyond Death': 'THB',
    'Ikoria: Lair of Behemoths': 'IKO',
    'Zendikar Rising': 'ZNR',
    'Kaldheim': 'KHM',
    'Strixhaven: School of Mages': 'STX',
    'Dungeons & Dragons: Adventures in the Forgotten Realms': 'AFR',
    'Innistrad: Midnight Hunt': 'MID',
    'Innistrad: Crimson Vow': 'VOW',
    'Kamigawa: Neon Dynasty': 'NEO',
    'Streets of New Capenna': 'SNC',
    'Dominaria United': 'DMU',
    "The Brothers' War": 'BRO',
    'Phyrexia: All Will Be One': 'ONE',
    'March of the Machine': 'MOM',
    'March of the Machine: The Aftermath': 'MAT',
    'Wilds of Eldraine': 'WOE',
    'The Lost Caverns of Ixalan': 'LCI',
    'Murders at Karlov Manor': 'MKM',
    'Outlaws of Thunder Junction': 'OTJ',
    'Bloomburrow': 'BLB',
    'Duskmourn: House of Horror': 'DSK',
    'Aetherdrift': 'DFT',
    'Tarkir: Dragonstorm': 'TDM',
    'Final Fantasy': 'FIN',
    'Edge of Eternities': 'EOE',
    "Marvel's Spider-Man": 'SPM',
    'Avatar: The Last Airbender': 'TLA',
    'Lorwyn Eclipsed': 'TBA',
    'Secrets of Strixhaven': 'TBA',
    'Event set': 'TBA',
    'TBA': 'TBA',
    'Modern Horizons': 'MH1',
    'Modern Horizons 2': 'MH2',
    'The Lord of the Rings: Tales of Middle-earth': 'LTR',
    'Modern Horizons 3': 'MH3',
    'Portal': 'POR',
    'Portal Second Age': 'P02',
    'Portal Three Kingdoms': 'PTK',
    'Starter 1999': 'S99',
    'Starter 2000': 'S00',
    'Global Series: Jiang Yanggu & Mu Yanling': 'GS1',
    'Chronicles': 'CHR',
    'Anthologies': 'ATH',
    'Battle Royale Box Set': 'BRB',
    'Beatdown Box Set': 'BTD',
    'Deckmasters: Garfield vs. Finkel': 'DKM',
    'Duels of the Planeswalkers (decks)': 'DPA',
    'Modern Event Deck': 'MD1',
    'Mystery Booster': 'MB1',
    'Time Spiral Remastered': 'TSR',
    'Dominaria Remastered': 'DMR',
    'Ravnica Remastered': 'RVR',
    'Innistrad Remastered': 'INR',
    'Mystery Booster 2': 'MB2',
    'Duel Decks: Elves vs. Goblins': 'EVG',
    'Duel Decks: Jace vs. Chandra': 'DD2',
    'Duel Decks: Divine vs. Demonic': 'DDC',
    'Duel Decks: Garruk vs. Liliana': 'DDD',
    'Duel Decks: Phyrexia vs. the Coalition': 'DDE',
    'Duel Decks: Elspeth vs. Tezzeret': 'DDF',
    'Duel Decks: Knights vs. Dragons': 'DDG',
    'Duel Decks: Ajani vs. Nicol Bolas': 'DDH',
    'Duel Decks: Venser vs. Koth': 'DDI',
    'Duel Decks: Izzet vs. Golgari': 'DDJ',
    'Duel Decks: Sorin vs. Tibalt': 'DDK',
    'Duel Decks: Heroes vs. Monsters': 'DDL',
    'Duel Decks: Jace vs. Vraska': 'DDM',
    'Duel Decks: Speed vs. Cunning': 'DDN',
    'Duel Decks Anthology': 'DD3',
    'Duel Decks: Elspeth vs. Kiora': 'DDO',
    'Duel Decks: Zendikar vs. Eldrazi': 'DDP',
    'Duel Decks: Blessed vs. Cursed': 'DDQ',
    'Duel Decks: Nissa vs. Ob Nixilis': 'DDR',
    'Duel Decks: Mind vs. Might': 'DDS',
    'Duel Decks: Merfolk vs. Goblins': 'DDT',
    'Duel Decks: Elves vs. Inventors': 'DDU',
    'From the Vault: Dragons': 'DRB',
    'From the Vault: Exiled': 'V09',
    'From the Vault: Relics': 'V10',
    'From the Vault: Legends': 'V11',
    'From the Vault: Realms': 'V12',
    'From the Vault: Twenty': 'V13',
    'From the Vault: Annihilation': 'V14',
    'From the Vault: Angels': 'V15',
    'From the Vault: Lore': 'V16',
    'From the Vault: Transform': 'V17',
    'Signature Spellbook: Jace': 'SS1',
    'Signature Spellbook: Gideon': 'SS2',
    'Signature Spellbook: Chandra': 'SS3',
    'Premium Deck Series: Slivers': 'H09',
    'Premium Deck Series: Fire and Lightning': 'PD2',
    'Premium Deck Series: Graveborn': 'PD3',
    'Modern Masters': 'MMA',
    'Modern Masters 2015 Edition': 'MM2',
    'Eternal Masters': 'EMA',
    'Modern Masters 2017 Edition': 'MM3',
    'Iconic Masters': 'IMA',
    'Masters 25': 'A25',
    'Ultimate Masters': 'UMA',
    'Double Masters': '2XM',
    'Double Masters 2022 Edition': '2X2',
    'Commander Masters': 'CMM',
    "Deck Builder's Toolkit": 'w10',
    "Deck Builder's Toolkit (Refreshed Version)": 'w11',
    "Deck Builder's Toolkit (2012 Edition)": 'w12',
    "Deck Builder's Toolkit (2014 Core Set Edition)": 'w14',
    "Deck Builder's Toolkit (2015 Core Set Edition)": 'w15',
    "Deck Builder's Toolkit (Magic Origins Edition)": 'ORI',
    "Deck Builder's Toolkit (Shadows over Innistrad Edition)": 'w16',
    "Deck Builder's Toolkit (Amonkhet Edition)": 'w17',
    "Deck Builder's Toolkit (Ixalan Edition)": 'w17',
    'Zendikar Expeditions': 'EXP',
    'Kaladesh Inventions': 'MPS',
    'Amonkhet Invocations': 'MP2',
    'Guilds of Ravnica Mythic Edition': 'MED',
    'Ravnica Allegiance Mythic Edition': 'MED',
    'War of the Spark Mythic Edition': 'MED',
    'Strixhaven Mystical Archive': 'STA',
    "The Brothers' War Retro Artifacts": 'BRR',
    'Multiverse Legends': 'MUL',
    'Enchanting Tales': 'WOT',
    'Breaking News': 'OTP',
    'Jumpstart': 'JMP',
    'Jumpstart 2022': 'J22',
    'Foundations Jumpstart': 'J25',
    'Secret Lair Drop': 'SLD',
    '"Universes Within"': 'SLX',
    'Transformers': 'BOT',
    'Doctor Who': 'WHO',
    'Jurassic World': 'REX',
    'Fallout': 'PIP',
    'Assassin’s Creed': 'ACR',
    'Planechase': 'HOP',
    'Planechase 2012 Edition': 'PC2',
    'Planechase Anthology': 'PCA',
    'Archenemy': 'ARC',
    'Archenemy: Nicol Bolas': 'E01',
    'Commander 2011': 'CMD',
    "Commander's Arsenal": 'CM1',
    'Commander 2013 Edition': 'C13',
    'Commander 2014': 'C14',
    'Commander 2015': 'C15',
    'Commander 2016': 'C16',
    'Commander Anthology': 'CMA',
    'Commander 2017': 'C17',
    'Commander Anthology Volume II': 'CM2',
    'Commander 2018': 'C18',
    'Commander 2019': 'C19',
    'Commander 2020 / Ikoria Commander': 'C20',
    'Zendikar Rising Commander': 'ZNC',
    'Commander Legends': 'CMR',
    'Kaldheim Commander': 'KHC',
    'Commander 2021 / Strixhaven Commander': 'C21',
    'Forgotten Realms Commander': 'AFC',
    'Midnight Hunt Commander': 'MIC',
    'Crimson Vow Commander': 'VOC',
    'Neon Dynasty Commander': 'NEC',
    'New Capenna Commander': 'NCC',
    "Battle for Baldur's Gate / Commander Legends 2": 'CLB',
    'Warhammer 40,000 Commander': '40K',
    "The Brothers' War Commander": 'BRC',
    'Wilds of Eldraine Commander': 'WOC',
    'Conspiracy': 'CNS',
    'Conspiracy: Take the Crown': 'CN2',
    'Explorers of Ixalan': 'E02',
    'Battlebond': 'BBD',
    "Collector's Edition": 'CED',
    "International Collector's Edition": 'CEI',
    'Unglued': 'UGL',
    'Unhinged': 'UNH',
    'Unstable': 'UST',
    'Unsanctioned': 'UND',
    'Unfinity': 'UNF',
    'Masters Edition': 'MED',
    'Masters Edition II': 'ME2',
    'Masters Edition III': 'ME3',
    'Masters Edition IV': 'ME4',
    'Vintage Masters': 'VMA',
    'Tempest Remastered': 'TPR'}


def run(input_file: str):
    # output
    fieldnames = [
        "Count", "Tradelist Count", "Name", "Edition", "Condition", "Language",
        "Foil", "Tags", "Last Modified", "Collector Number", "Alter", "Proxy", "Purchase Price"
    ]
    writer = csv.DictWriter(sys.stdout, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
    writer.writeheader()

    # input
    fin = open(input_file)
    reader = csv.DictReader(fin)
    for row in reader:
        # Last Modified
        date_added = (row.get("date_added") or "").strip()
        if date_added:
            try:
                dt = datetime.fromisoformat(date_added)
                last_modified = dt.strftime("%Y-%m-%d %H:%M:%S.%f")
            except ValueError:
                last_modified = date_added  # pass through if odd format
        else:
            last_modified = ""

        # Edition (map full set name to code; fallback to set_name)
        set_name = (row.get("set_name") or "").strip()
        edition = set_name_to_code.get(set_name, set_name)

        # Collector Number (strip leading '#')
        collector_number = (row.get("discriminator") or "").lstrip("#")

        out = {
            "Count": row.get("quantity", ""),
            "Tradelist Count": row.get("quantity", ""),
            "Name": row.get("product_name", ""),
            "Edition": edition,
            "Condition": row.get("grade_subtype", ""),
            "Language": "English",
            "Foil": "",
            "Tags": "",
            "Last Modified": last_modified,
            "Collector Number": collector_number,
            "Alter": "False",
            "Proxy": "False",
            "Purchase Price": ""
        }
        writer.writerow(out)


if __name__ == "__main__":
    input_file = sys.argv[1]
    run(input_file)